# @package _global_

defaults:
  - /datasets/hpatches/setup/ICCV2023/htune/rel_pose/h_opencv/num_2k/lowe_ratio@_global_

datasets:
  dataset_name: 'hpatches'
  evaluation_task: 'rel_pose'
  backend: 'h_opencv/2k'

  hpatches:
    loader:
      features:
        batch_size: 1
        num_samples: 6
        sampler: 'subset'

      htune:
        batch_size: 3
        num_samples: 3
        sampler: 'subset'
