eval_params:
  estimator:
    name: "E_PYOPENGV"
    confidence: 0.99999
    num_ransac_iter: 5000
    min_num_inliers: 7
  tuner:
    matcher:
      lowe_ratio:
        start: 0.85
        end: 1.0
        step: 0.01
    estimator:
      inl_thresh:
        start: 0.6
        end: 3.6
        step: 0.2
  shi_hardnet:
    matcher:
      lowe_ratio: 0.94
    estimator:
      inl_thresh: 2.2
  sift_hardnet:
    matcher:
      lowe_ratio: 0.95
    estimator:
      inl_thresh: 2.0
  superpoint_hardnet:
    matcher:
      lowe_ratio: 0.93
    estimator:
      inl_thresh: 2.2
  r2d2_hardnet:
    matcher:
      lowe_ratio: 0.92
    estimator:
      inl_thresh: 2.4
  keynet_hardnet:
    matcher:
      lowe_ratio: 0.93
    estimator:
      inl_thresh: 2.2
  disk_hardnet:
    matcher:
      lowe_ratio: 0.92
    estimator:
      inl_thresh: 2.2
  rekd_hardnet:
    matcher:
      lowe_ratio: 0.89
    estimator:
      inl_thresh: 2.2
  shiness_hardnet:
    matcher:
      lowe_ratio: 0.9
    estimator:
      inl_thresh: 2.2
