              # @package _global_
defaults:
- /models/shiss_disk/default: features_htune_test

models:
  model_name: shiss#flt@thr0-004_disk
  log_dir: shiss_disk/filtering/thr0-004
  shiss:
    eval_params:
      score_thresh: 0.004
