          # @package _global_

defaults:
- /models/shiness_disk/default: features_htune_test

models:
  model_name: shiness#h@scale2-828_disk
  log_dir: shiness_disk/homography/scale2-828
  shiness:
    checkpoint:
      rel_path: models/shiness/homography/scale2-828
      name: r_mAA-t_mAA=0.6773
