# @package _global_

defaults:
  - /models/logness: detector
  - /models/disk: descriptor

models:
  model_name: logness_disk
  log_dir: logness_disk

  logness:
    checkpoint:
      rel_path: models/logness/filtering/thr0-017
      name: r_mAA-t_mAA=0.6865

    htune:
      forward_modules:

    test:
      forward_modules:

  disk:
    htune:
      forward_modules:

    test:
      forward_modules: