              # @package _global_
defaults:
- /models/shirs_disk/default: features_htune_test

models:
  model_name: shirs#flt@thr0-005_disk
  log_dir: shirs_disk/filtering/thr0-005
  shirs:
    eval_params:
      score_thresh: 0.005
