        # @package _global_
defaults:
- /models/shiness_disk/default: custom

models:
  model_name: shiness#flt@thr0-000_disk
  shiness:
    checkpoint:
      rel_path: train/shiness/filtering/thr0-000
      name: r_mAA-t_mAA=0.6587
