custom:
  csv_path: "/mnt/sda/datasets/HPatches/test_pairs.csv"
  data_options:
    - 'image'
    - 'h'

  process: True

  transforms:
    grayscale:

    resize:
      width: -1
      height: -1

    crop:
      type: 'divisor_crop'
