# @package _global_

defaults:
  - /models/superpoint: detector
  - /models/hardnet: descriptor

models:
  model_name: 'superpoint_hardnet'
  log_dir: 'superpoint_hardnet'

  superpoint:
    htune:
      forward_modules:

    test:
      forward_modules:

  hardnet:
    modules:
      descriptor:
        idx: 2
        process_idx: 2

    htune:
      forward_modules:

    test:
      forward_modules:
