          # @package _global_

defaults:
- /models/shiness_disk/default: features_htune_test

models:
  model_name: shiness#h@scale1-681_disk
  log_dir: shiness_disk/homography/scale1-681
  shiness:
    checkpoint:
      rel_path: models/shiness/homography/scale1-681
      name: r_mAA-t_mAA=0.6950
