train:
  ss_loss:
    nms_size: 5
    score_thresh: 0.017
    topk: 1024

    scale_factor: 2.0
    num_samples: 100

    ablations:
      filtering:
        tag_pattern: 'flt@thr{:.3f}'
        log_pattern: 'thr{:.3f}'
        sweep_param: 'score_thresh'
        sweep_values:
          - 0.0
          - 0.01
          - 0.013
          - 0.015
          - 0.017
          - 0.019
