#input_size_divisor: 16
#
#modules:
#  detector:
#    idx: 0
#    default_idx: 0
#    process_idx: 0
#
#    min_ness: 0.0
#    max_ness: 32.0
#
#    scales:
#      - 0.8408964152537145
#      - 0.7071067811865476
#      - 0.5946035575013605
##      - 0.5
#
#    unet:
#      feature_channels: 3
#
#      down:
#        - 16
#        - 32
#        - 64
#        - 64
#        - 64
#
#      up:
#        - 64
#        - 64
#        - 64
#        - 2
#
#    shi:
#      sobel_size: 3
#      window_size: 3
#      window_cov: 2
#
#      loc: True
#
#eval_params:
#  nms_size: 5
#  shi_thresh: 0
