# @package _global_

defaults:
  - /datasets/imcpt/features/val
  - /datasets/imcpt/val/rel_pose/num_2k
  - /datasets/base/loader/features@datasets.imcpt.loader
  - /datasets/base/loader/test@datasets.imcpt.loader
  - /datasets/base/evaluation/features/num_2k@datasets.imcpt.evaluation
  - /datasets/base/evaluation/test/rel_pose@datasets.imcpt.evaluation

datasets:
  dataset_name: "imcpt"
  evaluation_task: 'rel_pose'
  backend: 'f_pydegensac/2k'
