input_channels: 1

modules:
  detector:
    idx: 0
    default_idx: 0
    process_idx: 0

    sobel_size: 3
    window_size: 3
    window_cov: 2

    harris_score: True

    loc: True

eval_params:
  nms_size: 5
  score_thresh: 0.0
