        # @package _global_
defaults:
- /models/shiness_disk/default: features_htune_test

models:
  model_name: shiness#flt@thr0-005_disk
  log_dir: shiness_disk/filtering/thr0-005
  shiness:
    checkpoint:
      rel_path: models/shiness/filtering/thr0-005
      name: r_mAA-t_mAA=0.6871
