eval_params:
  estimator:
    name: F_PYDEGENSAC
    confidence: 0.9999
    num_ransac_iter: 200000
    min_num_inliers: 7
  tuner:
    matcher:
      lowe_ratio:
        start: 0.93
        end: 1.0
        step: 0.01
    estimator:
      inl_thresh:
        start: 0.5
        end: 1.7
        step: 0.1
  shi_disk:
    matcher:
      lowe_ratio: 0.98
    estimator:
      inl_thresh: 0.8
  sift_disk:
    matcher:
      lowe_ratio: 0.99
    estimator:
      inl_thresh: 0.9
  superpoint_disk:
    matcher:
      lowe_ratio: 0.95
    estimator:
      inl_thresh: 1.3
  r2d2_disk:
    matcher:
      lowe_ratio: 0.99
    estimator:
      inl_thresh: 1.1
  keynet_disk:
    matcher:
      lowe_ratio: 0.99
    estimator:
      inl_thresh: 1.1
  disk:
    matcher:
      lowe_ratio: 0.98
    estimator:
      inl_thresh: 0.7
  rekd_disk:
    matcher:
      lowe_ratio: 0.98
    estimator:
      inl_thresh: 1.1
  shiness_disk:
    matcher:
      lowe_ratio: 0.97
    estimator:
      inl_thresh: 0.6
