# @package _global_

defaults:
  - /datasets/scannet/setup/ICCV2023/htune/rel_pose/e_pyopengv/num_2k/inl_thresh@_global_

datasets:
  dataset_name: "scannet"
  evaluation_task: 'rel_pose'
  backend: 'e_pyopengv/2k'

  scannet:
    loader:
      htune:
        batch_size: 3
        num_samples: 3
        sampler: 'subset'
