input_size_divisor: 16

modules:
  detector:
    idx: 0
    default_idx: 0
    process_idx: 0

    ners:
      feature_channels: 3

      down:
        - 16
        - 32
        - 64
        - 64
        - 64

      up:
        - 64
        - 64
        - 64
        - 1

    shi:
      sobel_size: 3
      window_size: 3
      window_cov: 2

      loc: True

eval_params:
  nms_size: 5
  score_thresh: 0.0

