# @package _global_

defaults:
  - /datasets/imcpt/setup/ICCV2023/train_val/rel_pose/f_pydegensac/num_2k@_global_

datasets:
  imcpt:
    loader:
      features:
        batch_size: 1
        num_samples: 6
        sampler: 'subset'

      test:
        batch_size: 3
        num_samples: 3
        sampler: 'subset'
