        # @package _global_
defaults:
- /models/dohness_disk/default: features_htune_test

models:
  model_name: dohness#flt@thr0-0000_disk
  log_dir: dohness_disk/filtering/thr0-0000
  dohness:
    checkpoint:
      rel_path: models/dohness/filtering/thr0-0000
      name: r_mAA-t_mAA=0.6605
