              # @package _global_
defaults:
- /models/shirs_disk/default: features_htune_test

models:
  model_name: shirs#flt@thr0-004_disk
  log_dir: shirs_disk/filtering/thr0-004
  shirs:
    eval_params:
      score_thresh: 0.004
