# @package _global_

defaults:
  - /models/log: detector
  - /models/disk: descriptor

models:
  model_name: 'log_disk'
  log_dir: 'log_disk'

  log:
    htune_rel_pose:
      forward_modules:

    test_rel_pose:
      forward_modules:

    test:
      forward_modules:

  disk:
    htune_rel_pose:
      forward_modules:

    test_rel_pose:
      forward_modules:

    test:
      forward_modules:
