# @package _global_

defaults:
  - /datasets/hpatches/htune/num_2k
  - /datasets/base/loader/htune@datasets.hpatches.loader
  - /datasets/hpatches/evaluation/htune/rel_pose/inl_thresh@datasets.hpatches.evaluation

datasets:
  dataset_name: 'hpatches'
  evaluation_task: 'rel_pose'
  backend: 'h_opencv/2k'
