# @package _global_

defaults:
  - /datasets/hpatches/features/val
  - /datasets/hpatches/htune/num_2k
  - /datasets/base/loader/features@datasets.hpatches.loader
  - /datasets/base/loader/htune@datasets.hpatches.loader
  - /datasets/hpatches/evaluation/features/num_2k@datasets.hpatches.evaluation
  - /datasets/hpatches/evaluation/htune/rel_pose/lowe_ratio@datasets.hpatches.evaluation

datasets:
  dataset_name: "hpatches"
  evaluation_task: 'rel_pose'
  backend: 'h_opencv/2k'
