# @package _global_

defaults:
  - /models/shiss: detector
  - /models/disk: descriptor

models:
  model_name: 'shiss_disk'
  log_dir: 'shiss_disk'

  shiss:
    htune:
      forward_modules:

    test:
      forward_modules:

    eval_params:
      ablations:
        filtering:
          tag_pattern: 'flt@thr{:.3f}'
          log_pattern: 'thr{:.3f}'
          sweep_param: 'score_thresh'
          sweep_values:
            - 0.0
            - 0.002
            - 0.003
            - 0.004
            - 0.005
            - 0.006
            - 0.007

  disk:
    htune:
      forward_modules:

    test:
      forward_modules:
