# @package _global_

defaults:
  - /models/shiness: detector
  - /models/disk: descriptor

models:
  model_name: 'shiness_disk'

  shiness:
    checkpoint:
      rel_path: "models/shiness"
      name: "r_mAA=0.7706"
