# @package _global_

defaults:
  - /models/dohness: detector
  - /models/disk: descriptor

models:
  model_name: dohness_disk

  dohness:
    checkpoint:
      rel_path: models/dohness/filtering/thr0-0006
      name: r_mAA-t_mAA=0.6674
