# @package _global_

defaults:
  - /datasets/imcpt/setup/ICCV2023/htune/rel_pose/f_pydegensac/num_2k/lowe_ratio@_global_

datasets:
  dataset_name: "imcpt"
  evaluation_task: 'rel_pose'
  backend: 'f_pydegensac/2k'

  imcpt:
    loader:
      features:
        batch_size: 1
        num_samples: 6
        sampler: 'subset'

      htune:
        batch_size: 3
        num_samples: 3
        sampler: 'subset'
