# @package _global_

defaults:
  - /models/harris: detector
  - /models/disk: descriptor

models:
  model_name: 'harris_disk'
  log_dir: 'harris_disk'

  harris:
    htune_rel_pose:
      forward_modules:

    test_rel_pose:
      forward_modules:

    test:
      forward_modules:

  disk:
    htune_rel_pose:
      forward_modules:

    test_rel_pose:
      forward_modules:

    test:
      forward_modules:
