input_channels: 3

input_size_divisor: 16

modules:
  descriptor:
    idx: 1
    default_idx: 1
    process_idx: 1

checkpoint:
  name: "depth-save"
  rel_path: "models/disk"
  remap: True

eval_params:
  matcher:
    name: 'l2'
