        # @package _global_
defaults:
- /models/logness_disk/default: custom

models:
  model_name: logness#flt@thr0-017_disk
  logness:
    checkpoint:
      rel_path: models/logness/filtering/thr0-017
      name: r_mAA-t_mAA=0.6865
